# Generated by Django 2.2.28 on 2024-02-08 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0005_auto_20240207_1740'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
